import type { Metadata } from "next";
import { Poppins, Inter, Lato } from "next/font/google";
import "./globals.css";
const lato = Poppins({
  display: "swap",
  weight: ["300", "400", "700", "900"],
  subsets: ['latin'],
  fallback: ["sans"],
  variable: "--font-main"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-screen overflow-x-hidden">

      <body
        className={`${lato.variable} antialiased px-8 lg:px-16 bg-primary-bg`}
      >
        {children}
      </body>
    </html>
  );
}
